def find_error_connect():
    try:

        return True
    except:
        return False